apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  replicas: 3
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
      - name: conversao-temperatura
        image: anderdull/conversao-temperatura:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
# deixar a aplicacao acessivel pelo balanceador
apiVersion: v1 
kind: Service
metadata:
  name: conversao-temperatura
spec:
  selector:
    app: conversao-temperatura
  ports:
  - port: 80 #(porta do container)
    targetPort: 8080 #(porta da aplicacao)
    nodePort: 30000 #(porta do loadbalancer)
  type: NodePort #(tipo do balanceamento)
